# Generated by Django 3.1.5 on 2021-02-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=15)),
                ('real_name', models.CharField(max_length=15)),
                ('tz', models.CharField(max_length=25)),
                ('activity_periods', models.CharField(max_length=1000)),
            ],
        ),
    ]
